          xxxxxxx
          -------
          xxxxxxx

          xxxxxxx
          -------
          xxxxxxx

x|x x|x             x|x x|x
x|x x|x     x|x     x|x x|x
x|x x|x     x|x     x|x x|x
x|x x|x             x|x x|x
x|x x|x     x|x     x|x x|x
x|x x|x     x|x     x|x x|x
x|x x|x             x|x x|x

          xxxxxxx
          -------
          xxxxxxx

          xxxxxxx
          -------
          xxxxxxx







